### ISSUE TITLE
Missing permissions from master permission list

### ISSUE THREAD

**Issue by celik0311** [Netflix-Skunkworks/policyuniverse#104]
Getting the below error, I think that the data.json file needs to be updated.

```
Exception: Desired action not found in master permission list. datacatalog:*
Exception: Desired action not found in master permission list. gluejobexecutor:*
```

**Comment by patricksanders** [comment]
Hey @celik0311, thanks for the report. Looks like our automatic updates have been failing for a while. I'll take a look and try to get this fixed.

**Comment by patricksanders** [comment]
We've fixed the auto-update! Closing this issue, please ping back if this is still a problem for you.

**Comment by scriptsrc** [comment]
What was wrong with it?

**Comment by patricksanders** [comment]
PhantomJS was failing in the updater action for ~6 months. After an embarrassing amount of troubleshooting, upgrading NodeJS fixed the issue. https://github.com/Netflix-Skunkworks/policyuniverse/commit/0562bbcbd7326c0c3a82ccbcfa3a0be2084fb209#diff-3d0b1b4a8777563fd9dad3f53f896e64c5722f524a221f14d44ed6d071e468a3R19-R22
