### ISSUE TITLE
Unhandled exception ValueError when Token not found in statement._userid_internet_accessible()

### ISSUE THREAD

**Issue by Zenthere** [Netflix-Skunkworks/policyuniverse#146]
https://github.com/Netflix-Skunkworks/policyuniverse/blob/96336a5c51f0daa5cc832050b5668cd9a326e6cc/policyuniverse/statement.py#L325

_userid_internet_accessible uses string.index() which throws an ValueError if the token is not present. This should be changed to string.find() which returns -1 if the token is not found.

*Reproduce*
Have an S3 bucket policy with UserId value that does not contain a "*"

**Comment by patricksanders** [comment]
Thanks for reporting @Zenthere!
