### ISSUE TITLE
(question) .github/workflows/updater.yml seems to have stop working?

### ISSUE THREAD

**Issue by smoy** [Netflix-Skunkworks/policyuniverse#184]
The Updater GitHub Action seems to have failed for quite some time. I attempt to run it in my own aws account; however, phantomjs doesn't seem to progress on the awsconsole.js

It's possible the AWS website has evolved enough that makes the updater un-reliable anymore. 

I have a proposal is to use https://github.com/iann0036/iam-dataset as a data repository. What would be a good way to adapt iam-dataset is the data input and continue to Netflix policyuniverse as the python API?

Cheers.

**Comment by aryangosling** [comment]
I guess, this is now unmaintained

**Comment by patricksanders** [comment]
Hey @smoy, sorry for missing this before. This project is still maintained, though it has not been something we've been able to prioritize. I'm definitely open to changing how the updater works. We come through and fix it occasionally, but it's super brittle and ends up breaking again shortly after.

I think the easiest approach for using a different dataset would be to modify the updater to pull the dataset and coerce it into the same structure that we [currently store](https://github.com/Netflix-Skunkworks/policyuniverse/blob/master/policyuniverse/data.json).

Here's the current updater logic that pulls the data from the console:
https://github.com/Netflix-Skunkworks/policyuniverse/blob/b436a90546cb2af319ba6f9bc1b777a0a547d053/updater/updater.py#L113-L134
