### ISSUE TITLE
Why cannot policies with deny actions be minimized?

### ISSUE THREAD

**Issue by jaythemishra** [Netflix-Skunkworks/policyuniverse#31]
I'm currently using policyuniverse to expand policies attached to IAM Users in an AWS account, remove actions not being used by the user by referencing AWS CloudTrail event logs, and return the modified policies. However, sometimes the expanded policy is longer than the character limit allowed by AWS (e.g. 6,144 characters for managed policies), and sometimes these policies cannot be minimized by policyunverse because they contain deny actions. Is there a reason why this is the case? I may be missing something, but isn't the process for minimizing allow actions the same as minimizing deny actions?

**Comment by scriptsrc** [comment]
It should be easy to modify `policyuniverse` to handle Deny statements as well.

FYI - What you're doing sounds like `repokid` - https://github.com/Netflix/Repokid

Some eventNames in Cloudtrail don't line up with the permission name.
Some permissions aren't recorded in CloudTrail at all.
Some services don't log to cloudtrail.

`iam:passrole` does not show up in cloudtrail.
