### ISSUE TITLE
Updating the data.json source file

### ISSUE THREAD

**Issue by amarah247** [Netflix-Skunkworks/policyuniverse#37]
Hello,

How is the source file generated? Manually or otherwise? Is there a way to generate the latest version of the data.json file? 

Thanks

**Comment by scriptsrc** [comment]
Hey @amarah247 - 

So it actually logs into the AWS console with phantomjs and imitates the AWS console to generate the data.

I'll see if we can make that updater code available.

**Comment by kmcquade** [comment]
@scriptsrc i thought it was from the policies.js file in the AWS policy generator static site?

**Comment by scriptsrc** [comment]
@kmcquade - nah -

It calls `/iam/api/services` to get a list of all the services:

```
        jQuery.ajax({
            type: "GET",
            url: "/iam/api/services",
```

Then it iterates over each returned service to get the action details.

```
 var actions_url = service_data['_links']['actions']['href'];
```
...
```

        jQuery.ajax({
            type: "GET",
            url: actions_url,
            dataType: 'json',
```

It's basically scraping the service description files from the console. I don't think the `policies.js` file had all the information I was looking for. Maybe it was missing action groups or links to documentation or something.

**Comment by jsmartin** [comment]
FWIW, policysentry does this by scraping the AWS Documentation.  Not sure if that pattern would work here based on your requirements:

https://github.com/salesforce/policy_sentry/blob/40f33899868a23814906c325cf7d83eedf77f7e1/policy_sentry/shared/awsdocs.py

**Comment by scriptsrc** [comment]
Just PR'd the auto-updater:
