### ISSUE TITLE
Understanding policyuniverse source data

### ISSUE THREAD

**Issue by lvh** [Netflix-Skunkworks/policyuniverse#7]
I ended up writing some code that is pretty similar to this before I knew this project existed. Where does the source JSON data come from? Is it manually curated, or is it extracted from the Policy Editor JSON? (It appears to be the latter, but I'm not sure :))

**Comment by lvh** [comment]
(One of the reasons I ask is because PolicyUniverse is missing Snowball, which the upstream PolicyGen happens to be missing too :))

**Comment by monkeysecurity** [comment]
Hey @lvh  - Just back from a really long leave.

https://github.com/Netflix-Skunkworks/policyuniverse/blob/master/policyuniverse/__init__.py#L22

^ The comments there show where the data comes from.

Tl;dr is that we pull it out of the AWS console. 

I’ll update this in the next couple days to have the recent permissions.

Really wish AWS provided an API to obtain these.
