### ISSUE TITLE
s3:listobjects not listed as action

### ISSUE THREAD

**Issue by mr26** [Netflix-Skunkworks/policyuniverse#76]
Hello,

It appears that s3:listobjects is not listed when expanding on the actions of an appropriate Policy Statement, even though it is a valid API action.

For example, when expanding on the following statement:

`{'Effect': 'Allow', 'Action': '*', 'Resource': '*'}`

Only the following s3 actions are listed:

```
s3:listjobs
s3:getbucketpolicy
s3:deletebucketpolicy
s3:getbucketpolicystatus
s3:putbucketversioning
s3:putbucketpublicaccessblock
s3:getobjectversiontagging
s3:createaccesspoint
s3:abortmultipartupload
s3:getanalyticsconfiguration
s3:putobject
s3:putaccesspointpolicy
s3:getobjectversionacl
s3:replicatedelete
s3:deletebucketwebsite
s3:putreplicationconfiguration
s3:putbuckettagging
s3:putaccountpublicaccessblock
s3:createbucket
s3:createjob
s3:getinventoryconfiguration
s3:replicatetags
s3:getobjecttagging
s3:listallmybuckets
s3:updatejobstatus
s3:listbucketmultipartuploads
s3:getobjecttorrent
s3:restoreobject
s3:headbucket
s3:putobjectretention
s3:putbucketnotification
s3:getmetricsconfiguration
s3:getjobtagging
s3:putbucketwebsite
s3:putlifecycleconfiguration
s3:getaccesspoint
s3:deletejobtagging
s3:getobject
s3:getobjectretention
s3:getbucketlogging
s3:updatejobpriority
s3:getobjectlegalhold
s3:replicateobject
s3:getobjectacl
s3:listbucket
s3:getbucketversioning
s3:putobjectversionacl
s3:getbucketobjectlockconfiguration
s3:putbucketcors
s3:describejob
s3:listbucketversions
s3:putbucketpolicy
s3:getobjectversion
s3:getbucketnotification
s3:deleteobjecttagging
s3:getobjectversiontorrent
s3:putobjectversiontagging
s3:getbuckettagging
s3:putobjecttagging
s3:getbucketpublicaccessblock
s3:getaccountpublicaccessblock
s3:putbucketrequestpayment
s3:putaccelerateconfiguration
s3:bypassgovernanceretention
s3:getlifecycleconfiguration
s3:deleteobjectversion
s3:putobjectlegalhold
s3:listaccesspoints
s3:putmetricsconfiguration
s3:getbucketrequestpayment
s3:deletebucket
s3:objectowneroverridetobucketowner
s3:deleteobject
s3:getbucketlocation
s3:deleteaccesspoint
s3:deleteobjectversiontagging
s3:putbucketacl
s3:getaccelerateconfiguration
s3:putencryptionconfiguration
s3:putanalyticsconfiguration
s3:putinventoryconfiguration
s3:getbucketwebsite
s3:getbucketacl
s3:putbucketobjectlockconfiguration
s3:getencryptionconfiguration
s3:getaccesspointpolicy
s3:listmultipartuploadparts
s3:putobjectacl
s3:getbucketcors
s3:getobjectversionforreplication
s3:getaccesspointpolicystatus
s3:putjobtagging
s3:putbucketlogging
s3:getreplicationconfiguration
s3:deleteaccesspointpolicy
```

**Comment by mr26** [comment]
It appears that s3:listobjectversions is not listed either

**Comment by scriptsrc** [comment]
Hey @mr26. PolicyUniverse simply pulls the information from the AWS Console. Those permissions were removed/replaced in the AWS Console. See below:


`s3:listobjects` was replaced with `s3:listbucket`:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html

s3:ListBucket
Description
Grants permission to list some or all of the objects in an Amazon S3 bucket (up to 1000) Learn more 

**Supported resource types**
bucket

**Supported condition keys**
s3:DataAccessPointAccount
s3:DataAccessPointArn
s3:max-keys
s3:AccessPointNetworkOrigin
s3:x-amz-content-sha256
s3:signatureAge
s3:authType
s3:delimiter
s3:prefix
s3:signatureversion

-----

`s3:listobjectversions` was replaced with `s3:listbucketversions`:

https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html

**s3:ListBucketVersions**
Description
Grants permission to list metadata about all the versions of objects in an Amazon S3 bucket Learn more 

**Supported resource types**
bucket

**Supported condition keys**
s3:DataAccessPointAccount
s3:DataAccessPointArn
s3:max-keys
s3:AccessPointNetworkOrigin
s3:x-amz-content-sha256
s3:signatureAge
s3:authType
s3:delimiter
s3:prefix
s3:signatureversion
